# Generated by Django 4.1 on 2022-09-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='desc1',
            new_name='adesc',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='img1',
            new_name='aimg',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='name1',
            new_name='anam',
        ),
    ]
